// feshop/src/app/site/header/header.component.ts
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { Component, HostBinding, HostListener, Inject, OnInit, PLATFORM_ID, TemplateRef, ViewChild, effect, inject, signal } from '@angular/core';
import { AppService } from '../../app.service';
import { MatMenuModule } from '@angular/material/menu';
import { MainComponent } from '../main/main.component';
import { MatBadgeModule } from '@angular/material/badge';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { DanhmucService } from '../../admin/main-admin/danhmuc/danhmuc.service';
import { OverlayModule } from '@angular/cdk/overlay';
import { GiohangService } from '../../admin/main-admin/website/giohang/giohang.service';
import { Sidebar, SidebarModule } from 'primeng/sidebar';
import { ButtonModule } from 'primeng/button';
import { MegaMenuModule } from 'primeng/megamenu';
import { InputTextModule } from 'primeng/inputtext';
import { MegaMenuItem } from 'primeng/api';
import { UsersService } from '../../admin/users/auth/users.service';
import { LocalStorageService } from '../../shared/localstorage.service';
import { AuthService } from '../../admin/users/auth/auth.service';
import { FlatTreeControl } from '@angular/cdk/tree';
import { MatTreeFlatDataSource, MatTreeFlattener, MatTreeModule } from '@angular/material/tree';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatInputModule } from '@angular/material/input';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon';
import { SanphamService } from '../../admin/main-admin/sanpham/sanpham.service';
import { MatSnackBar } from '@angular/material/snack-bar';
import { SanphamblockComponent } from '../../sanpham/sanphamblock/sanphamblock.component';
import { DonhangsService } from '../../admin/donhang/listdonhang/listdonhang.service';
@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    CommonModule,
    MatMenuModule,
    RouterLinkActive,
    MatBadgeModule,
    RouterLink,
    OverlayModule,
    SidebarModule,
    ButtonModule,
    MegaMenuModule,
    InputTextModule,
    MatTreeModule,
    MatInputModule,
    FormsModule,
    MatButtonModule,
    MatIconModule,
    MatDialogModule,
    SanphamblockComponent
  ],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  isOpen = false;
  // isOpen:any = false;
  _AppService: AppService = inject(AppService);
  _MainComponent: MainComponent = inject(MainComponent);
  _DanhmucService: DanhmucService = inject(DanhmucService);
  _DonhangsService: DonhangsService = inject(DonhangsService);
  _UsersService: UsersService = inject(UsersService);
  _AuthService: AuthService = inject(AuthService);
  _SanphamService: SanphamService = inject(SanphamService);
  _Router: Router = inject(Router);
  _LocalStorageService: LocalStorageService = inject(LocalStorageService);
  SearchParams: any = {
    Status:1,
    pageSize: 50,
    pageNumber: 0,
    Type:'sanpham',
  };
  darkmode: boolean = false
  Danhmucs: any = {}
  User: any = {}
  Timkiem:any
  Token:any=this._LocalStorageService.getItem('token') ?? null;
  @ViewChild('sidebarRef') sidebarRef!: Sidebar;

  closeCallback(e: any): void {
    this.sidebarRef.close(e);
  }

  sidebarVisible: boolean = false;
  Menus: any[] = []

  private _transformer = (node: any, level: number) => {
    return {
      expandable: !!node.children && node.children.length > 0,
      Title: node.Title,
      Slug: node.Slug,
      level: level,
    };
  };
  treeControl = new FlatTreeControl<any>(
    node => node.level,
    node => node.expandable,
  );
  treeFlattener = new MatTreeFlattener(
    this._transformer,
    node => node.level,
    node => node.expandable,
    node => node.children,
  );
  dataSource = new MatTreeFlatDataSource(this.treeControl, this.treeFlattener);
  hasChild = (_: number, node: any) => node.expandable;
  Today:any= new Date()
  Donhang = signal<any>({});
  Timkiems:any=[]
  constructor(
    private dialog:MatDialog,
    private _snackBar:MatSnackBar,
    @Inject(PLATFORM_ID) private platformId: Object
  ) {
    this._AppService.isDarkTheme$.subscribe(isDarkTheme => {
      if (isPlatformBrowser(this.platformId)) {
        // Access 'document' safely in the browser environment
        document.body.classList.toggle('dark', isDarkTheme);
      }
      // document.body.classList.toggle('dark', isDarkTheme);
    });

  }
  Soluong = 0
  Tongcong = 0
  options: string[] = ['Option 1', 'Option 2', 'Option 3'];
  selectedOption: string = '';

  async ngOnInit(): Promise<void> {
    this._DonhangsService.DonhangInit()
    this.Donhang = this._DonhangsService.Donhang  
    if(this.Token)
    {
      this._UsersService.getProfile().then((data) => {
        if (data) {
          this.User = data
          // console.log(data); 
        }
      })
    }
    this.Danhmucs = await this._DanhmucService.SearchDanhmuc(this.SearchParams)
    this.Menus =[
    { id: 1, Title: 'Về Chúng Tôi', Slug: 'blog/gioi-thieu/ve-chung-toi' },
    {
      id: 2, Title: 'Sản Phẩm', Slug: 'danh-muc', Show: false,
      children:this.Danhmucs.items
    },
    { id: 3, Title: 'Khuyến Mãi', Slug: 'blog/khuyen-mai' },
    { id: 4, Title: 'Món Ngon', Slug: 'blog/mon-ngon-moi-ngay' },
    { id: 5, Title: 'Tin tức', Slug: 'blog/tin-tuc' },
    // {
    //   id: 3, Title: 'Về chúng tôi ', Slug: 've-chung-toi', Show: false,
    //   children: [
    //     { id: 101, Title: 'Giới Thiệu Chung', Slug: 'gioi-thieu-chung' },
    //     // { id: 102, Title: 'Qui Trình', Slug: 'quy-trinh' },
    //     // { id: 103, Title: 'Hỏi Đáp', Slug: 'hoi-dap' },
    //     // { id: 104, Title: 'Tuyển Dụng', Slug: 'tuyen-dung' },
    //   ]
    // },
    { id: 3, Title: 'Liên hệ', Slug: 'lien-he' },
  ]
  this.dataSource.data = this.Menus;
  }

  GetTongCong()
  {
    return this.Donhang()?.Giohangs?.reduce((acc: any, item: any) => acc + item.Tongtien, 0);  
  }
  onSelect(option: string) {
    this.selectedOption = option;
  }

  toggleTheme() {
    this._AppService.toggleTheme();
  }
  toggleDrawer() {
    this._MainComponent.drawer.toggle()
  }
  onMouseEnter(name: string) {
    console.log("mouse enter", name);
  }
  onMouseOut(name: string) {
    console.log("mouse out", name);
  }
  Dangxuat()
  {
    const result = this._AuthService.Dangxuat()
    if(result){
      window.location.href ='/'
    }
  }
  TimkiemDialog(teamplate: TemplateRef<any>): void {
    const dialogRef = this.dialog.open(teamplate, {
    });
    dialogRef.afterClosed().subscribe(() => {
        this.Timkiems = []
    });
  }
  async DoSearch(event: Event) {
    const value = (event.target as HTMLInputElement).value;
    if (value.length > 1) {
      const Sanpham = await this._SanphamService.SearchSanpham({Query:value,Status:1})
      console.log(Sanpham);
      this.Timkiems = Sanpham.items
    }
    else {
      this.Timkiems = []
    }
  }
}

<div class="relative lg:bg-[#57A345] bg-white">
    <div class="lg:block hidden w-full h-full">
        <div class="h-full grid grid-cols-11">
            <div class="bg-white my-1"></div>
            <a href="/" class="col-span-3 p-2 flex items-center justify-end pe-10 me-4 rounded-r-full bg-white my-1">
                <img loading="lazy" src="/assets/images/logo-full.png" class="max-h-20">
            </a>
            <div class="col-span-5 flex flex-col space-y-2 py-2 cursor-pointer justify-center">
                <div class="flex flex-row space-x-16 items-center">
                    <div class="hidden lg:flex flex-row space-x-3 text-white">
                        @for(item of Menus; track item) {
                        @if (item.children!=null&&item.children.length>0) {
                        <div class="group relative">
                            <a [href]="[item.Slug]"
                                class="flex flex-row items-center header-link py-2 font-semibold uppercase transition-all">
                                {{item.Title}}
                                <span class="material-symbols-outlined">
                                    expand_more
                                </span>
                            </a>
                            @if (item.id==2) {
                            <div class="absolute w-[80vw] -translate-x-1/2 left-1/2 text-black z-10 hidden group-hover:grid border rounded-lg grid-cols-3 gap-4 bg-white p-4"
                                (mouseleave)="Menus[$index].Show=false">
                                @for (item of item.children; track item.id) {
                                <div class="flex flex-row space-x-2 items-center">
                                    @if(item && item.Image&&item.Image.Thumb)
                                    {
                                    <img loading="lazy" src="assets/images/sanpham/{{item.Image.Thumb}}" class="h-10">
                                    }
                                    @else if(item && item.Image&&item.Image.Hinhchinh&&item.Image.Hinhchinh.src){
                                    <img loading="lazy" src="{{item.Image.Hinhchinh.src}}" class="h-10">
                                    }
                                    @else {
                                    <img loading="lazy" src="assets/images/noimage.png" class="p-3 max-h-10 rounded-lg">
                                    }
                                    <a href="danh-muc/{{item.Slug}}">{{item.Title}}</a>
                                </div>
                                }
                            </div>
                            }
                            @else {
                            <div class="border rounded-lg grid grid-cols-1 gap-4 bg-white p-4"
                                (mouseleave)="Menus[$index].Show=false">
                                @for (item of item.children; track item.id) {
                                <a href="{{item.Slug}}" class="">{{item.Title}}</a>
                                }
                            </div>
                            }
                        </div>
                        }
                        @else {
                        <a class="flex flex-row items-center header-link py-2 font-semibold uppercase transition-all"
                            [href]="[item.Slug]">
                            <span class="text-sm border-r px-2">
                                {{item.Title}}
                            </span>
                        </a> }
                        }
                    </div>
                </div>
                <div class="flex flex-row space-x-2 items-center w-full">
                    <span class="material-symbols-outlined font-bold text-[#FAA61A] !2text-lg rounded-full border-2 border-[#FAA61A] p-2">call</span>
                    <a href="tel:0865770009" class="text-[#FAA61A] font-bold text-lg">0865.77.0009</a>
                    <div class="relative w-1/2" (click)="TimkiemDialog(dialogTimkiem)">
                        <input
                            class="hidden lg:block w-full py-2 px-4 pe-10 text-sm 
                text-gray-900 border border-gray-300 rounded-full bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Tìm Kiếm" />
                        <div class="lg:absolute inset-y-0 end-0 flex items-center lg:pe-3 cursor-pointer">
                            <button mat-icon-button>
                                <span class="material-symbols-outlined lg:text-gray-400 text-white">
                                    search
                                </span>
                            </button>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-span-2 flex flex-col space-y-3 py-2 justify-center">
                <div class="justify-start items-center">
                    @if(this.Token){
                    <div class="mx-2 flex flex-row space-x-2 items-center cursor-pointer text-white">
                        <a routerLink="/profile">
                            <img loading="lazy" [src]="User?.Image?.Main||'/assets/images/noimage.png'"
                            class="rounded-full w-10 h-10 border">
                        </a>
                        <!-- <a routerLink="/admin" class="underline">
                            <span>Admin</span>
                        </a> -->
                        <a (click)="Dangxuat()" class="underline">
                                <span>Đăng Xuất</span>
                        </a>
                    </div>

                    }
                    @else {

                    <div class="hidden lg:flex flex-row space-x-2 items-center text-white">
                        <a href="dangnhap" class="px-2 underline">
                            Đăng Nhập
                        </a>
                    </div>
                    <div class="lg:hidden">
                        <a href="dangnhap" mat-icon-button>
                            <span class="material-symbols-outlined text-white">
                                person
                            </span>
                        </a>
                    </div>
                    }
                    <mat-menu #user="matMenu" xPosition="before">
                        <button mat-menu-item>
                            <a routerLink="/profile" routerLinkActive="bg-gray-200"
                                class="flex flex-row space-x-3 items-center">
                                <span class="material-symbols-outlined">manage_accounts</span>
                                <span>Tài Khoản</span>
                            </a>
                        </button>
                        <button mat-menu-item>
                            <a routerLink="/admin" routerLinkActive="bg-gray-200"
                                class="flex flex-row space-x-3 items-center">
                                <span class="material-symbols-outlined">account_circle</span>
                                <span>Admin</span>
                            </a>
                        </button>
                        <a (click)="Dangxuat()" mat-menu-item>
                            <div class="flex flex-row space-x-3 items-center">
                                <span class="material-symbols-outlined">logout</span>
                                <span>Đăng Xuất</span>
                            </div>
                        </a>
                    </mat-menu>
                </div>



                <div class="flex flex-row space-x-1 items-center w-full">
                    <div class="relative">
                        <a href="don-hang" mat-icon-button matBadgeColor="warn">
                            <span class="material-symbols-outlined text-white">shopping_cart</span>
                        </a>
                        <span
                            class="absolute font-bold -top-1 right-0 bg-white text-red-500 text-xs px-2 py-1 rounded-full">
                            {{(Donhang()?.Giohangs?.length||0| number:'1.0-0')}}
                        </span>
                    </div>
                    <a href="don-hang" class="text-white">
                        {{(GetTongCong()||0 | number:'1.0-0')}}đ
                    </a>
                </div>
                <div class="lg:hidden">
                    <button mat-icon-button (click)="sidebarVisible = true">
                        <span class="material-symbols-outlined text-white">
                            menu
                        </span>
                    </button>
                </div>


            </div>
        </div>
    </div>

    <div class="lg:hidden flex flex-col w-full h-full">
        <div class="w-full flex flex-row justify-between items-center px-4">
            <button mat-icon-button (click)="sidebarVisible = true">
                <span class="material-symbols-outlined text-[#E1232A]">
                    menu
                </span>
            </button>
            <a href="/" class="p-2">
                <img loading="lazy" src="/assets/images/logo-full.png" class="max-h-12">
            </a>
            <div class="flex flex-row space-x-2 items-center justify-center">
                <!-- <div class="flex flex-row space-x-16 items-center justify-center">
                    @if(this.Token){
                    <img loading="lazy" [src]="User?.Image?.Main||'/assets/images/noimage.png'"
                        class="rounded-full w-10 h-10 border" [matMenuTriggerFor]="user">
                    }
                    @else {

                    <div class="hidden lg:flex flex-row space-x-2 text-xs items-center !text-[#E1232A]">
                        <a href="dangnhap" class="border-r px-2">
                            Đăng Nhập
                        </a>
                        <a href="dangky">
                            Đăng Ký
                        </a>
                    </div>
                    <div class="lg:hidden">
                        <a href="dangnhap" mat-icon-button>
                            <span class="material-symbols-outlined !text-[#E1232A]">
                                person
                            </span>
                        </a>
                    </div>
                    }
                </div> -->
                <div class="relative">
                    <a href="don-hang" mat-icon-button matBadgeColor="warn">
                        <span class="material-symbols-outlined !text-[#E1232A]">shopping_cart</span>
                    </a>
                    <span
                        class="absolute font-bold -top-1 right-0 !bg-[#E1232A] text-white text-xs px-2 py-1 rounded-full">
                        {{(Donhang()?.Giohangs?.length||0| number:'1.0-0')}}
                    </span>
                </div>
                <a href="don-hang" class="!text-[#E1232A]">
                    {{(GetTongCong()||0 | number:'1.0-0')}}đ
                </a>
            </div>
        </div>
        <!-- <div class="cursor-pointer flex flex-col space-y-2 justify-center items-center">
            <a class="flex flex-row items-center space-x-2 text-[#FAA61A]" href="tel:0865770009">
                <span class="material-symbols-outlined">smartphone</span>
                <span> Điện Thoại: 0865.77.0009</span>
            </a>
            //
            <a href="email:rausachtrangia@gmail.com" class="flex flex-row items-center space-x-2 text-[#FAA61A]" href="tel:0865770009">
                <span class="material-symbols-outlined">mail</span>
                <span>rausachtrangia&#64;gmail.com</span>
            </a>
            <div class="relative w-1/2" (click)="TimkiemDialog(dialogTimkiem)">
                <input
                    class="w-full py-2 px-4 pe-10 text-sm 
        text-gray-900 border border-gray-300 rounded-full bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    placeholder="Tìm Kiếm" />
                <div class="absolute inset-y-0 end-0 flex items-center lg:pe-3 cursor-pointer">
                    <button mat-icon-button>
                        <span class="material-symbols-outlined text-gray-400">
                            search
                        </span>
                    </button>
                </div>
            </div>
        </div> -->

        <div class="flex flex-row space-x-2 items-center justify-between w-full bg-[#57A345] p-2">
            <span class="material-symbols-outlined font-bold text-[#FAA61A] !2text-lg rounded-full border-2 border-[#FAA61A] p-2">call</span>
            <a href="tel:0865770009" class="text-[#FAA61A] font-bold text-lg">0865.77.0009</a>
            <div class="relative w-1/2" (click)="TimkiemDialog(dialogTimkiem)">
                <input
                    class="w-full py-2 px-4 pe-10 text-sm 
        text-gray-900 border border-gray-300 rounded-full bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    placeholder="Tìm Kiếm" />
                <div class="absolute inset-y-0 end-0 flex items-center lg:pe-3 cursor-pointer">
                    <button mat-icon-button>
                        <span class="material-symbols-outlined text-gray-400">
                            search
                        </span>
                    </button>
                </div>
            </div>
        </div>
        <div class="cursor-pointer flex flex-row space-x-4 font-bold text-[#E1232A] items-center justify-center bg-gray-100 py-2">
           @if(this.Token){
            <div (click)="Dangxuat()">Đăng Xuất</div>
           }
           @else{
            <a href="dangnhap">Đăng Nhập</a>
            <span>|</span>
            <a href="dangky">Đăng Ký</a>
           }
            <span>|</span>
            <a href="don-hang">Giỏ Hàng</a>
        </div>
        <!-- <div class="relative w-2/3 mx-auto" (click)="TimkiemDialog(dialogTimkiem)">
            <input class="w-full py-2 px-4 pe-10 text-sm bg-gray-100
    text-gray-900 border border-gray-300 rounded-full" placeholder="Tìm Kiếm" />
            <div class="absolute inset-y-0 end-0 flex items-center lg:pe-3 cursor-pointer">
                <button mat-icon-button>
                    <span class="material-symbols-outlined text-gray-400">
                        search
                    </span>
                </button>
            </div>

        </div> -->
    </div>






    <p-sidebar [(visible)]="sidebarVisible" class="z-10" position="left" class="w-1/2">
        <ng-template pTemplate="header">
            <a href="/">
                <img loading="lazy" src="/assets/images/logo.webp" class="lg:h-20 h-10">
            </a>
        </ng-template>
        <ng-template pTemplate="content">
            <mat-tree [dataSource]="dataSource" [treeControl]="treeControl">
                <mat-tree-node *matTreeNodeDef="let node" matTreeNodePadding>
                    <button mat-icon-button disabled></button>
                    <a href="{{node.Slug}}">{{node.Title}}</a>
                </mat-tree-node>
                <mat-tree-node *matTreeNodeDef="let node;when: hasChild" matTreeNodePadding>
                    <button mat-icon-button matTreeNodeToggle [attr.aria-label]="'Toggle ' + node.Title">
                        <span
                            class="material-symbols-outlined">{{treeControl.isExpanded(node)?'expand_more':'navigate_next'}}</span>
                    </button>
                    <a href="{{node.Slug}}">{{node.Title}}</a>
                </mat-tree-node>
            </mat-tree>
            <div>
                @if(this.Token){
                <div class="w-full flex flex-row justify-between">
                    <div class="flex flex-row space-x-2 items-center">
                        <img loading="lazy" [src]="User?.Image?.Main||'/assets/images/noimage.png'"
                            class="rounded-full w-10 h-10 border">
                        <span class="font-bold">{{User.Hoten||"Guest"}}</span>
                    </div>

                    <a (click)="Dangxuat()">
                        <button mat-icon-button>
                            <span class="material-symbols-outlined">
                                logout
                            </span>

                        </button>
                    </a>


                </div>
                }
                @else {
                <div class="flex flex-row space-x-2 items-center">
                    <a href="dangnhap" class="p-2 border rounded-full 
                                bg-slate-200 text-blue-500 
                                hover:bg-blue-500 hover:text-white">
                        Đăng Nhập
                    </a>
                    <a href="dangky" class="p-2 border rounded-full 
                          bg-slate-200 text-blue-500 
                          hover:bg-blue-500 hover:text-white">
                        Đăng Ký
                    </a>
                </div>
                }
            </div>
        </ng-template>
        <ng-template pTemplate="footer">
            <div class="text-pgray-400 text-sm text-center">
                <p>© Copyright {{Today|date:'yyyy'}}</p>
            </div>
        </ng-template>
    </p-sidebar>
    <ng-template #dialogTimkiem>
        <div
            class="relative lg:max-h-[90vh] lg:w-[50vw] max-h-[90vh] w-[90vw] flex flex-col justify-between space-y-2 lg:p-8 p-3 divide-y">
            <div class="relative flex flex-row space-x-2 items-center">
                <mat-form-field appearance="outline" subscriptSizing="dynamic" class="w-full">
                    <input matInput (input)="DoSearch($event)" placeholder="Tìm Kiếm">
                    <span matPrefix class="p-2 material-symbols-outlined">search</span>
                </mat-form-field>
                <div mat-dialog-actions>
                    <button class="ml-auto" mat-flat-button color="primary" mat-dialog-close="false">Đóng</button>
                </div>
            </div>
            <div class="relative flex flex-col space-y-2 h-full w-full overflow-auto p-3">
                @if(Timkiems.length>0){
                <div class="grid lg:grid-cols-4 grid-cols-2 justify-between">
                    @for (item of Timkiems; track item.id) {

                    <app-sanphamblock [Detail]="item" [isMuangay]="false"></app-sanphamblock>

                    <!-- <div class="flex flex-col space-y-2">
                        <a href="san-pham/{{item.Slug}}" class="z-10 grid grid-cols-1 border rounded-lg p-3 bg-white">
                            @if(item && item.Image&&item.Image.Main)
                            {
                            <img loading="lazy" src="assets/images/sanpham/{{item.Image.Main}}" class="w-full">
                            }
                            @else if(item && item.Image&&item.Image.Hinhchinh&&item.Image.Hinhchinh.src){
                            <img loading="lazy" src="{{item.Image.Hinhchinh.src}}" class="w-full">
                            }
                            @else if(item && item.Image&&item.Image.Hinhchinh&&item.Image.Hinhchinh.src){
                            <img loading="lazy" src="assets/images/noimage.png" class="p-3 w-full mx-auto rounded-lg">
                            }
                            <div (click)="AddtoCart(item);$event.preventDefault()"
                                class="z-20 flex flex-row space-x-2 justify-end items-end">
                                <span
                                    class="z-10 material-symbols-outlined rounded-lg p-2 bg-[#57A345] text-white hover:bg-[#afe8a2]">shopping_cart</span>
                            </div>
                        </a>
                        <div class="flex flex-col justify-center">
                            <span class="text-base text-center font-bold line-clamp-1">{{item.Title}}</span>
                            <p class="text-gray-400 text-[13px] line-clamp-2" [innerHTML]="item.Mota"></p>
                            <div class="flex flex-row justify-center">
                                <div class="relative p-4">
                                    <img loading="lazy" src="assets/images/pricetag.svg" class="h-8">
                                    <div
                                        class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex flex-row">
                                        <span class="text-white font-bold"> {{item?.Giagoc[0]?.gia|
                                            number:'1.0-0'}}đ/{{item?.Giagoc[0]?.khoiluong}}{{item?.Giagoc[0]?.dvt}}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    }

                </div>
                }
                @else{

                <span class="text-center font-bold">Không tìm thấy kết quả</span>
                }
            </div>
            <!-- <div mat-dialog-actions class="absolute top-0 right-0">
                <button class="ml-auto" mat-flat-button color="primary" mat-dialog-close="false">x</button>
            </div> -->
        </div>

        <!-- <div class="lg:w-[40vw] lg:h-[40vh] h-[95vh] flex flex-col justify-between space-y-3 divide-x-2">
        <div mat-dialog-content>
            <div class="flex flex-col w-full space-y-4 p-2">
                <mat-form-field appearance="outline" class="w-full !text-xs">
                    <input matInput (input)="DoSearch($event)"  placeholder="Tìm Kiếm">
                    <span matPrefix class="p-2 material-symbols-outlined">search</span>
                </mat-form-field>
                <div class="">
                    @for (item of Timkiems; track item.id) {
                        <div class="p-2 rounded-lg bg-slate-50">
                            <span>{{item.Title}}</span>
                        </div> 
                    }
                </div>
            </div>
        </div>
        <div mat-dialog-actions class="flex items-end">
            <button class="ml-auto" mat-flat-button color="primary"  mat-dialog-close="false">Đóng</button>
        </div>
    </div> -->
    </ng-template>
</div>

// site/src/components/layout/Header.tsx
'use client'

import { useState, useEffect } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { Search, ShoppingCart, Menu, Phone, User, LogOut } from 'lucide-react'
import { useAuthStore } from '@/store/auth'
import { useCartStore } from '@/store/cart'
import { categoryService } from '@/services/category.service'
import { productService } from '@/services/product.service'
import { Category, Product } from '@/types'
import { getImageSrc, formatNumber } from '@/lib/utils'
import SearchDialog from '@/components/ui/SearchDialog'
import MobileMenu from '@/components/ui/MobileMenu'

export default function Header() {
  const [isSticky, setIsSticky] = useState(false)
  const [categories, setCategories] = useState<Category[]>([])
  const [searchOpen, setSearchOpen] = useState(false)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [searchResults, setSearchResults] = useState<Product[]>([])
  const [isSearching, setIsSearching] = useState(false)

  const { user, isAuthenticated, logout } = useAuthStore()
  const { items, getTotalItems, getTotalPrice } = useCartStore()

  useEffect(() => {
    const handleScroll = () => {
      setIsSticky(window.scrollY > 80)
    }
    
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  useEffect(() => {
    // Load categories for menu
    const loadCategories = async () => {
      try {
        const data = await categoryService.getCategoryTree()
        setCategories(data)
      } catch (error) {
        console.error('Failed to load categories:', error)
      }
    }
    
    loadCategories()
  }, [])

  const handleSearch = async (query: string) => {
    if (query.length < 2) {
      setSearchResults([])
      return
    }

    setIsSearching(true)
    try {
      const result = await productService.searchProducts({
        Query: query,
        Status: 1,
        pageSize: 12,
        pageNumber: 0
      })
      setSearchResults(result.items)
    } catch (error) {
      console.error('Search failed:', error)
      setSearchResults([])
    } finally {
      setIsSearching(false)
    }
  }

  const getUserImageSrc = (): string => {
    if (!user?.Image) return '/assets/images/noimage.png'
    
    if (user.Image.Main) {
      if (user.Image.Main.startsWith('http')) {
        return user.Image.Main
      }
      return `/assets/images/${user.Image.Main}`
    }
    
    if (user.Image.Hinhchinh?.src) {
      return user.Image.Hinhchinh.src
    }
    
    return '/assets/images/noimage.png'
  }

  const getCategoryImageSrc = (category: Category): string => {
    if (!category.Image) return '/assets/images/noimage.png'
    
    if (category.Image.Thumb) {
      return getImageSrc(category.Image.Thumb, 'thumb')
    }
    
    if (category.Image.Hinhchinh?.src) {
      return category.Image.Hinhchinh.src
    }
    
    return '/assets/images/noimage.png'
  }

  const menus = [
    { id: 1, Title: 'Về Chúng Tôi', Slug: '/blog/gioi-thieu/ve-chung-toi' },
    {
      id: 2, 
      Title: 'Sản Phẩm', 
      Slug: '/danh-muc', 
      children: categories
    },
    { id: 3, Title: 'Khuyến Mãi', Slug: '/blog/khuyen-mai' },
    { id: 4, Title: 'Món Ngon', Slug: '/blog/mon-ngon-moi-ngay' },
    { id: 5, Title: 'Tin tức', Slug: '/blog/tin-tuc' },
    { id: 6, Title: 'Liên hệ', Slug: '/lien-he' },
  ]

  return (
    <>
      <div className={`relative lg:bg-[#57A345] bg-white transition-all duration-300 ${isSticky ? 'fixed top-0 left-0 right-0 z-50 shadow-lg' : ''}`}>
        {/* Desktop Header */}
        <div className="lg:block hidden w-full h-full">
          <div className="h-full grid grid-cols-11">
            <div className="bg-white my-1"></div>
            
            {/* Logo */}
            <Link href="/" className="col-span-3 p-2 flex items-center justify-end pe-10 me-4 rounded-r-full bg-white my-1">
              <Image 
                src="/assets/images/logo-full.png" 
                alt="Rau Sạch Trần Gia"
                width={200}
                height={80}
                className="max-h-20 w-auto"
              />
            </Link>
            
            {/* Navigation & Search */}
            <div className="col-span-5 flex flex-col space-y-2 py-2 cursor-pointer justify-center">
              <div className="flex flex-row space-x-16 items-center">
                <div className="hidden lg:flex flex-row space-x-3 text-white">
                  {menus.map((item) => (
                    <div key={item.id} className="group relative">
                      <Link
                        href={item.Slug}
                        className="flex flex-row items-center header-link py-2 font-semibold uppercase transition-all hover:text-[#FAA61A]"
                      >
                        {item.Title}
                        {item.children && (
                          <span className="material-symbols-outlined ml-1">expand_more</span>
                        )}
                      </Link>
                      
                      {/* Mega Menu for Products */}
                      {item.id === 2 && item.children && (
                        <div className="absolute w-[80vw] -translate-x-1/2 left-1/2 text-black z-10 hidden group-hover:grid border rounded-lg grid-cols-3 gap-4 bg-white p-4 shadow-lg">
                          {item.children.map((category) => (
                            <div key={category.id} className="flex flex-row space-x-2 items-center py-2">
                              <Image
                                src={getCategoryImageSrc(category)}
                                alt={category.Title}
                                width={40}
                                height={40}
                                className="h-10 w-10 object-cover rounded"
                              />
                              <Link 
                                href={`/danh-muc/${category.Slug}`}
                                className="hover:text-[#57A345] transition-colors duration-200"
                              >
                                {category.Title}
                              </Link>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
              
              {/* Phone & Search */}
              <div className="flex flex-row space-x-2 items-center w-full">
                <Phone className="text-[#FAA61A] border-2 border-[#FAA61A] rounded-full p-2 w-10 h-10" />
                <Link href="tel:0865770009" className="text-[#FAA61A] font-bold text-lg">
                  0865.77.0009
                </Link>
                <div className="relative w-1/2">
                  <input
                    type="text"
                    onClick={() => setSearchOpen(true)}
                    className="w-full py-2 px-4 pe-10 text-sm text-gray-900 border border-gray-300 rounded-full bg-gray-50 focus:ring-blue-500 focus:border-blue-500 cursor-pointer"
                    placeholder="Tìm Kiếm"
                    readOnly
                  />
                  <div 
                    className="absolute inset-y-0 end-0 flex items-center pe-3 cursor-pointer"
                    onClick={() => setSearchOpen(true)}
                  >
                    <Search className="w-5 h-5 text-gray-400" />
                  </div>
                </div>
              </div>
            </div>
            
            {/* User & Cart */}
            <div className="col-span-2 flex flex-col space-y-3 py-2 justify-center">
              <div className="justify-start items-center">
                {isAuthenticated && user ? (
                  <div className="mx-2 flex flex-row space-x-2 items-center text-white">
                    <Link href="/profile">
                      <Image
                        src={getUserImageSrc()}
                        alt={user.Hoten || 'User'}
                        width={40}
                        height={40}
                        className="rounded-full w-10 h-10 border object-cover"
                      />
                    </Link>
                    <button 
                      onClick={logout}
                      className="underline hover:text-[#FAA61A] transition-colors"
                    >
                      Đăng Xuất
                    </button>
                  </div>
                ) : (
                  <div className="hidden lg:flex flex-row space-x-2 items-center text-white">
                    <Link href="/dangnhap" className="px-2 underline hover:text-[#FAA61A] transition-colors">
                      Đăng Nhập
                    </Link>
                  </div>
                )}
              </div>
              
              {/* Cart */}
              <div className="flex flex-row space-x-1 items-center w-full">
                <div className="relative">
                  <Link href="/don-hang">
                    <ShoppingCart className="w-6 h-6 text-white" />
                    {getTotalItems() > 0 && (
                      <span className="absolute font-bold -top-1 right-0 bg-white text-red-500 text-xs px-2 py-1 rounded-full min-w-[20px] text-center">
                        {formatNumber(getTotalItems())}
                      </span>
                    )}
                  </Link>
                </div>
                <Link href="/don-hang" className="text-white text-sm">
                  {formatNumber(getTotalPrice())}đ
                </Link>
              </div>
            </div>
          </div>
        </div>
        
        {/* Mobile Header */}
        <div className="lg:hidden flex flex-col w-full h-full">
          <div className="w-full flex flex-row justify-between items-center px-4 py-2">
            <button onClick={() => setMobileMenuOpen(true)}>
              <Menu className="w-6 h-6 text-[#E1232A]" />
            </button>
            
            <Link href="/" className="p-2">
              <Image 
                src="/assets/images/logo-full.png" 
                alt="Rau Sạch Trần Gia"
                width={120}
                height={48}
                className="max-h-12 w-auto"
              />
            </Link>
            
            <div className="flex flex-row space-x-2 items-center">
              <div className="relative">
                <Link href="/don-hang">
                  <ShoppingCart className="w-6 h-6 text-[#E1232A]" />
                  {getTotalItems() > 0 && (
                    <span className="absolute font-bold -top-1 right-0 bg-[#E1232A] text-white text-xs px-2 py-1 rounded-full min-w-[20px] text-center">
                      {formatNumber(getTotalItems())}
                    </span>
                  )}
                </Link>
              </div>
              <Link href="/don-hang" className="text-[#E1232A] text-sm">
                {formatNumber(getTotalPrice())}đ
              </Link>
            </div>
          </div>
          
          {/* Mobile Contact & Search */}
          <div className="flex flex-row space-x-2 items-center justify-between w-full bg-[#57A345] p-2">
            <Phone className="text-[#FAA61A] border-2 border-[#FAA61A] rounded-full p-2 w-10 h-10" />
            <Link href="tel:0865770009" className="text-[#FAA61A] font-bold text-lg">
              0865.77.0009
            </Link>
            <div className="relative w-1/2">
              <input
                type="text"
                onClick={() => setSearchOpen(true)}
                className="w-full py-2 px-4 pe-10 text-sm text-gray-900 border border-gray-300 rounded-full bg-gray-50 cursor-pointer"
                placeholder="Tìm Kiếm"
                readOnly
              />
              <div 
                className="absolute inset-y-0 end-0 flex items-center pe-3 cursor-pointer"
                onClick={() => setSearchOpen(true)}
              >
                <Search className="w-5 h-5 text-gray-400" />
              </div>
            </div>
          </div>
          
          {/* Mobile Auth Links */}
          <div className="flex flex-row space-x-4 font-bold text-[#E1232A] items-center justify-center bg-gray-100 py-2">
            {isAuthenticated ? (
              <button onClick={logout} className="hover:text-[#C51D23] transition-colors">
                Đăng Xuất
              </button>
            ) : (
              <>
                <Link href="/dangnhap" className="hover:text-[#C51D23] transition-colors">
                  Đăng Nhập
                </Link>
                <span>|</span>
                <Link href="/dangky" className="hover:text-[#C51D23] transition-colors">
                  Đăng Ký
                </Link>
              </>
            )}
            <span>|</span>
            <Link href="/don-hang" className="hover:text-[#C51D23] transition-colors">
              Giỏ Hàng
            </Link>
          </div>
        </div>
      </div>
      
      {/* Search Dialog */}
      <SearchDialog 
        open={searchOpen}
        onOpenChange={setSearchOpen}
        onSearch={handleSearch}
        results={searchResults}
        isLoading={isSearching}
      />
      
      {/* Mobile Menu */}
      <MobileMenu 
        open={mobileMenuOpen}
        onOpenChange={setMobileMenuOpen}
        menus={menus}
        user={user}
        isAuthenticated={isAuthenticated}
        onLogout={logout}
      />
    </>
  )
}
